### ISSUE TITLE
token name length not in parameters when running elven-tools nft-minter issue-collection-token

### ISSUE THREAD

**Issue by tannerhallman** [ElvenTools/elven-tools-cli#2]
Firstly, amazing work. Thanks for this cli. Great examples and I appreciate it.. Trying it for you.

Ran into an issue where it looks like there may be a required param that isn't making it to the SC?

```
➜  elrond git:(feature/convert-deploy-nft-to-js) ✗ elven-tools nft-minter issue-collection-token
✔ Enter the name for the collection token (ex. MyName123).
Avoid spaces and special characters
 … HallmanitorTestCollection
✔ Enter the ticker for the collection token (ex. MYNAME).
Avoid spaces and special characters. Keep it short and capitalize.
 … HALM
Transaction: https://devnet-explorer.elrond.com/transactions/9f42afb9173d0e602a20b7690d593fc6ece9b282629062928a3a89eccabfd055
Your collection token id:  token name length not in parameters
Also saved in the output.json file.
```

output.json
```
{
  "nftMinterScAddress": "erd1qqqqqqqqqqqqqpgqgjgrpp23scs73dd65e3xewzepvcue50zx2dstypda3",
  "nftMinterScCollectionSellingPrice": "1000000000000000000",
  "nftMinterCollectionToken": "token name length not in parameters"
}
```

**Comment by tannerhallman** [comment]
Here was the previous two functions
```
➜  elrond git:(feature/convert-deploy-nft-to-js) ✗ elven-tools nft-minter issue-collection-token
✔ Enter the name for the collection token (ex. MyName123).
Avoid spaces and special characters
 … HallTest
✔ Enter the ticker for the collection token (ex. MYNAME).
Avoid spaces and special characters. Keep it short and capitalize.
 … HALLMT2
⠏ Processing transaction...TypeError: Cannot read property 'split' of undefined
    at /Users/tannerhallman/.nvm/versions/node/v14.18.0/lib/node_modules/elven-tools/build/index.js:36:989
    at Generator.next (<anonymous>)
    at i (/Users/tannerhallman/.nvm/versions/node/v14.18.0/lib/node_modules/elven-tools/build/index.js:2:880)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
⠸ Processing transaction...^C
➜  elrond git:(feature/convert-deploy-nft-to-js) ✗ elven-tools deploy nft-minter
✔ Decide if the contract can be upgraded in the future.
 › Yes
✔ Decide if the contract's storage can be read by other contracts. Not recommended in this case.
 › No
✔ Decide if the contract can receive funds. Recommended because of the royalties.
 › Yes
✔ Provide the base IPFS CID:
 … QmaDxkg6683EWQg4djhJjdof1w55AZR9Hypt8r3fvFRVHp
✔ Provide the base metadata files IPFS CID:
 … QmQWiPffwX9rWD9biVPUX7NksagefX2dKoBrXBzDLCRES1
✔ Provide the file extension:
 › .png
✔ Provide amount of tokens in collection:
 … 10
✔ Provide the seling price (ex. 0.5 for 0.5 EGLD):
 … 1
✔ Tokens limit per one address (ex 3 for three):
 … 100
✔ Provide the royalties value (ex. 20 for 20%) [optional]:
 … 10
✔ Provide tags (ex. tag1,tag2,tag3) [optional]:
 …
✔ Provide the provenance hash (sha256 hash of all images) [optional]:
 …
Deployment transaction executed: success
Transaction: https://devnet-explorer.elrond.com/transactions/176f31d97e23e3680c80ab0d5d55b158f9889e5239c14ae0e44b5a91d1b4c34e
Smart Contract address: erd1qqqqqqqqqqqqqpgqgjgrpp23scs73dd65e3xewzepvcue50zx2dstypda3
```

**Comment by tannerhallman** [comment]
I ran it again and it seemed to run fine

**Comment by juliancwirko** [comment]
I will add more data checks and validation for the token name length and the ticker. Thanks for reporting that.

**Comment by juliancwirko** [comment]
https://docs.elrond.com/developers/nft-tokens/#parameters-format

**Comment by juliancwirko** [comment]
added proper validation
